port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
experimental:
  ignore-resolve-fail: true
cfw-latency-timeout: 3000
cfw-latency-url: http://cp.cloudflare.com/generate_204
cfw-conn-break-strategy: true
secret: ""
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:8853
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - 223.6.6.6
    - 117.50.10.10
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.twnic.tw/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
